### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/template#3]
Something like this https://github.com/Schrodinger-Hat/schrodinger-hat-website

**Comment by piyush-sri** [comment]
Hello, I would like to update  the readme file.

**Comment by Wabri** [comment]
Thanks you 😁 you can fork the project, update the readme and open a pr!

**Comment by Wabri** [comment]
We could add also this: https://contrib.rocks/image?repo=schrodinger-hat/imagegonord

**Comment by abe-101** [comment]
@all-contributors please add @abe-101 for code doc
